<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- Change the width below to just wider than your form's width
    to optimize its initial scale on Apple iOS  and Android devices -->
    <meta name = "viewport" content="width=640">
<title>Approbation de pr&eacute;sentation</title>
<style>
<!--
body {background-color:#ffffff; font-family:verdana; font-size:12px; text-align:left; min-width: 500px; margin:50 0 0 0;}
p {line-height:18px;}
.container {background-color:#ffffff; width:640px; border:2px solid #999999; padding:5 5 15 5; margin-left:auto; margin-right:auto;}
.container2 {background-color:#ffffff; width:600px; border:0.5px solid #999999; padding:5 5 10 5; margin-left:auto; margin-right:auto;}
.pagetitle {background-color:#dddddd; padding:8px; font-size:16px; font-weight:bold; color:#000000; text-align:left;}
.pagetitlealert {background-color:#ff0000; padding:8px; font-size:16px; font-weight:bold; color:#ffffff; text-align:left;}
.pagetitlesuccess {background-color:#33cc00; padding:8px; font-size:16px; font-weight:bold; color:#ffffff; text-align:left;}
.formlabel {font-size:13px;}
.error {color:#ff0000; font-weight:bold; font-size:11px;}
.small {font-size:11px;}
-->
</style>
</head>
<body>

<div class="container">
<div align="left">
   <img style="width: 100px; height: 63px;" alt="JCertif Logo" src="cid:image"><br>
</div>

<div class="container2">
<div class="pagetitlesuccess">Bravo ! Proposition de pr&eacute;sentation est accept&eacute;e!</div>
<p>
   Bonjour $participant.salutation$ $participant.nom$ $participant.prenom$!<br />
   Votre proposition de pr&eacute;sentation &agrave; la conf&eacute;rence JCertif 2011 a &eacute;t&eacute; approuv&eacute;e.<br />
   <br />
   Vous pouvez d&egrave;s maintenant commencer &agrave; pr&eacute;parer votre d&eacute;placement pour les 3 et 4 Septembre 2011 &agrave; Brazzaville.
   <br />
   <br>Voici quelques information importantes:<b/><br />
  
   <lu>
   		<li>Nous fournir votre pr&eacute;f&eacute;rence pour la case horaire de votre pr&eacute;sentation (lien calendar).<li/> 
		<li>Nous fournir une pr&eacute;f&eacute;rence de la taille du T-Shirt sp&eacute;cial pour les pr&eacute;sentateurs JCertif 2011.<li/> 
		<li>Commencez &agrave; vous renseigner sur les possibilit&eacute;s d&#39;h&eacute;bergement et des moyens de transport.<li/>
		<li>Consultez notre page d&#39;information utiles (lien infoUtile).<li/>
	<ul/>
	
	<br>pr&eacute;sentation accept&eacute;e:<b/><br />
   <lu>
		<li>$propositionPresentation.titre$.<li/>
	<ul/>


   
   <br />
   Devenez vous aussi collecteur de votre secteur et et rejoingnez l&#39;&eacute;quipe d&#39;organisation !<br />
   N&#39;h&eacute;sitez pas &agrave; nous contacter pour plus d&#39;information. 
   <a href="mailto:info@jcertif.com?subject=Je%20souhaite%20devenir%20collecteur%20de%20mon%20secteur">Info@jcertif.com</a><br />
   <br />
   ================================================<br />
   &Eacute;quipe JCertif 2011 - <a href="http://www.jcertif.com/" target="_blank" style="color: rgb(0, 0, 204);">http://www.jcertif.com</a><br />
   Info@jcertif.com
</p>
</div>
<hr />

<div align="center">
<b>Sponsors<b/>
<table>
	<tr>
		$partenaires$
	</tr>
   		
</div>



</div>

</body>
</html>