<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- Change the width below to just wider than your form's width
    to optimize its initial scale on Apple iOS  and Android devices -->
    <meta name = "viewport" content="width=640">
<title>Proposition enr&eacute;gistr&eacute;e</title>
<style>
<!--
body {background-color:#ffffff; font-family:verdana; font-size:12px; text-align:left; min-width: 500px; margin:50 0 0 0;}
p {line-height:18px;}
.container {background-color:#ffffff; width:640px; border:2px solid #999999; padding:5 5 15 5; margin-left:auto; margin-right:auto;}
.container2 {background-color:#ffffff; width:600px; border:0.5px solid #999999; padding:5 5 10 5; margin-left:auto; margin-right:auto;}
.pagetitle {background-color:#dddddd; padding:8px; font-size:16px; font-weight:bold; color:#000000; text-align:left;}
.pagetitlealert {background-color:#ff0000; padding:8px; font-size:16px; font-weight:bold; color:#ffffff; text-align:left;}
.pagetitlesuccess {background-color:#33cc00; padding:8px; font-size:16px; font-weight:bold; color:#ffffff; text-align:left;}
.formlabel {font-size:13px;}
.error {color:#ff0000; font-weight:bold; font-size:11px;}
.small {font-size:11px;}
-->
</style>
</head>
<body>

<div class="container">
<div align="left">
   <img style="width: 100px;" alt="JCertif Logo" src="cid:image"><br>
</div>

<div class="container2">
<div class="pagetitlesuccess">Merci pour votre proposition de pr&eacute;sentation!</div>
<p>
   Merci $participant.salutation$ $participant.nom$ $participant.prenom$!<br />
   Votre proposition de pr&eacute;sentation &agrave; la conf&eacute;rence JCertif 2011 a bien &eacute;t&eacute; enregistr&eacute;e.<br />
   <br />
   L&#39;&eacute;quipe d&#39;approbation vous notifiera par email de la suite accord&eacute;e &agrave; votre proposition (accept&eacute;e or refus&eacute;e).<br />
   <br />
   R&egrave;gles g&eacute;n&eacute;rales de JCertif:<br />
   -------------------------------------<br />
   <lu>
   		<li>Les badges d&#39;acc&egrave;s VIP gratuits accord&eacute;s aux pr&eacute;sentateurs sont limit&eacute;s à 1 badge par pr&eacute;sentateur et ne peuventt être transf&eacute;r&eacute;s ou prêt&eacute;s à un tier.<li/> 
		<li>Le CongoJUG ne rembourse pas les frais de voyage ni tout autres d&eacute;penses occasionn&eacute;es par le d&eacute;placement des pr&eacute;sentateurs.<li/> 
		<li>En acceptant l&#39;invitation de pr&eacute;senter &agrave; JCertif, vous autorisez CongoJug &agrave; promouvoir, publier ou utiliser le contenu de votre pr&eacute;sentation pour les besoins de la conf&eacute;rence.<li/>
	<ul/>
   
   <br />
   Devenez vous aussi collecteur de votre secteur et et rejoingnez l&#39;&eacute;quipe d&#39;organisation !<br />
   N&#39;h&eacute;sitez pas &agrave; nous contacter pour plus d&#39;information. 
   <a href="mailto:info@jcertif.com?subject=Je%20souhaite%20devenir%20collecteur%20de%20mon%20secteur">Info@jcertif.com</a><br />
   <br />
   ================================================<br />
   &Eacute;quipe JCertif 2011 - <a href="http://www.jcertif.com/" target="_blank" style="color: rgb(0, 0, 204);">http://www.jcertif.com</a><br />
   Info@jcertif.com
</p>
</div>
<hr />

<div align="center">
<b>Sponsors<b/>
<table>
	<tr>
		$partenaires$
	</tr>
   		
</div>



</div>

</body>
</html>