<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- Change the width below to just wider than your form's width
    to optimize its initial scale on Apple iOS  and Android devices -->
    <meta name = "viewport" content="width=640">
<title>Inscription enr&eacute;gistr&eacute;e</title>
<style>
<!--
body {background-color:#ffffff; font-family:verdana; font-size:12px; text-align:left; min-width: 500px; margin:50 0 0 0;}
p {line-height:18px;}
.container {background-color:#ffffff; width:640px; border:2px solid #999999; padding:5 5 15 5; margin-left:auto; margin-right:auto;}
.container2 {background-color:#ffffff; width:600px; border:0.5px solid #999999; padding:5 5 10 5; margin-left:auto; margin-right:auto;}
.pagetitle {background-color:#dddddd; padding:8px; font-size:16px; font-weight:bold; color:#000000; text-align:left;}
.pagetitlealert {background-color:#ff0000; padding:8px; font-size:16px; font-weight:bold; color:#ffffff; text-align:left;}
.pagetitlesuccess {background-color:#33cc00; padding:8px; font-size:16px; font-weight:bold; color:#ffffff; text-align:left;}
.formlabel {font-size:13px;}
.error {color:#ff0000; font-weight:bold; font-size:11px;}
.small {font-size:11px;}
-->
</style>
</head>
<body>

<div class="container">
<div align="left">
   <img style="width: 100px; height: 63px;" alt="JCertif Logo" src="cid:image"><br>
</div>

<div class="container2">
<div class="pagetitlesuccess">Merci pour votre inscription !</div>
<p>
   Merci $participant.salutation$ $participant.nom$ $participant.prenom$!<br />
   Votre inscription &agrave; la conf&eacute;rence JCertif 2011 a bien &eacute;t&eacute; enregistr&eacute;e.<br />
   <br />
   Il ne vous reste que 2 petites &eacute;tapes pour compl&eacute;ter la proc&eacute;dure.<br />
   <br />
   &Eacute;tapes &agrave; suivre :<br />
   -------------------<br />
   &nbsp;1 - Contacter rapidement le collecteur de votre sercteur ( <a href="http://www.jcertif.com/node/33">http://www.jcertif.com/PageXXX</a>).<br />
   &nbsp;2 - Payer les frais de participation et recevez votre carte d&#39;invitation officielle et un num&eacute;ro de confirmation.<br />
   <br />
   Vous pouvez retourner &agrave; la page d&#39;accueil : <a href="http://www.jcertif.com/">http://www.jcertif.com</a><br />
   <br />
   <br />
   Devenez vous aussi collecteur de votre secteur et et rejoingnez l&#39;&eacute;quipe d&#39;organisation !<br />
   N&#39;h&eacute;sitez pas &agrave; nous contacter pour plus d&#39;information. 
   <a href="mailto:info@jcertif.com?subject=Je%20souhaite%20devenir%20collecteur%20de%20mon%20secteur">Info@jcertif.com</a><br />
   <br />
   ================================================<br />
   &Eacute;quipe JCertif 2011 - <a href="http://www.jcertif.com/" target="_blank" style="color: rgb(0, 0, 204);">http://www.jcertif.com</a><br />
   Info@jcertif.com
</p>
</div>
<hr />

<div align="center">
<b>Sponsors<b/>
<table>
	<tr>
		<td><img style="width: 100px; height: 63px;" alt="JCertif Logo" src="cid:image"></td>
		<td><img style="width: 100px; height: 63px;" alt="JCertif Logo" src="cid:image"></td>
		<td><img style="width: 100px; height: 63px;" alt="JCertif Logo" src="cid:image"></td>
		<td><img style="width: 100px; height: 63px;" alt="JCertif Logo" src="cid:image"></td>
		<td><img style="width: 100px; height: 63px;" alt="JCertif Logo" src="cid:image"></td>
		<td><img style="width: 100px; height: 63px;" alt="JCertif Logo" src="cid:image"></td>
	</tr>
   		
</div>



</div>

</body>
</html>