<html>
    <head>
        <meta content="text/html; charset=ISO-8859-1"
              http-equiv="content-type">
        <title>JCertif Confirmation Proposition Sujet</title>
    </head>
    <body>
        <center>
            <table style="border-style: solid; border-color: yellow; text-align: center; width: 620px; height: 448px; visibility: visible; list-style-type: disc; background-color: rgb(153, 255, 153);" border="0" cellpadding="2" cellspacing="2">
                <tbody>
                    <tr>
                        <td style="vertical-align: top;">
                            <img style="width: 100px; height: 63px;" alt="JCertif Logo" src="cid:image"><br>
                        </td>
                    </tr>
                    <tr>
                        <td style="vertical-align: top;">
                            <table
                                style="border-style: none; text-align: left; width: 608px; height: 290px;"
                                border="0" cellpadding="2" cellspacing="2">
                                <tbody>
                                    <tr>
                                        <th style="vertical-align: middle; text-align: center;">
                                            <big style="font-weight: bold; background-color: transparent; color: rgb(230, 184, 0);">
                                                <big>
                                                    <big>Merci pour votre participation!</big>
                                                </big>
                                            </big>
                                            <br>
                                        </th>
                                    </tr>
                                    <tr>
                                        <td style="vertical-align: top;">Merci!<br>
                                            <p>Votre proposition a bien été enregistrée.</p>
                                            <p>Il ne vous reste que 2 petites étapes pour compléter la
                                                procédure.<br>
                                                <br>
                                                Étapes à suivre :</p>
                                            <ol>
                                                <li>Contacter le collecteur de votre sercteur (<a
                                                        href="http://www.jcertif.com/node/33" target="_blank"
                                                        style="color: rgb(0, 0, 204);">http://www.jcertif.com/PageXXX</a><wbr>)</li>
                                                    <li>Payer les frais de participation et recevez votre
                                                        carte d'invitation
                                                        officielle avec votre numéro de confirmation. (<span
                                                            style="font-weight: bold; color: red;">Vous utiliserez le code
                                                            Participant pour vous identifier au cours de l'enregistrement)</span><br>
                                                    </li>
                                            </ol>

                                            <p>Vous pouvez retourner à la page d'accueil :&nbsp;<a
                                                    href="http://www.jcertif.com/" target="_blank"
                                                    style="color: rgb(0, 0, 204);">http://www.jcertif.com</a><br>
                                                <br>
                                                Vous aussi devenez collecteur de votre secteur et rejoingnez l'équipe
                                                d'organisation !<br>
                                                N'hésitez pas à nous contacter pour plus d'information.&nbsp;Info@jcertif.com<br>
                                            </p>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            Equipe JCertif 2011<br>
                            <a href="http://www.jcertif.com/" target="_blank" style="color: rgb(0, 0, 204);">http://www.jcertif.com</a><br>
                            Info@jcertif.com
                        </td>
                    </tr>
                    <tr>
                        <td style="vertical-align: top;"><br>
                        </td>
                    </tr>
                </tbody>
            </table>
            <br>
            <br>
        </center>
    </body>
</html>