<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- Change the width below to just wider than your form's width
    to optimize its initial scale on Apple iOS  and Android devices -->
    <meta name = "viewport" content="width=640">
<title>Proposition enr&eacute;gistr&eacute;e</title>
<style>
<!--
body {background-color:#ffffff; font-family:verdana; font-size:12px; text-align:left; min-width: 500px; margin:50 0 0 0;}
p {line-height:18px;}
.container {background-color:#ffffff; width:640px; border:2px solid #999999; padding:5 5 15 5; margin-left:auto; margin-right:auto;}
.container2 {background-color:#ffffff; width:600px; border:0.5px solid #999999; padding:5 5 10 5; margin-left:auto; margin-right:auto;}
.pagetitle {background-color:#dddddd; padding:8px; font-size:16px; font-weight:bold; color:#000000; text-align:left;}
.pagetitlealert {background-color:#ff0000; padding:8px; font-size:16px; font-weight:bold; color:#ffffff; text-align:left;}
.pagetitlesuccess {background-color:#33CC33; padding:8px; font-size:18px; font-weight:bold; color:#ffffff; text-align:left;}
.formlabel {font-size:13px;}
.error {color:#ff0000; font-weight:bold; font-size:11px;}
.small {font-size:11px;}
-->
</style>
</head>
<body>

<div class="container">
<div align="left">
   <img style="width: 100px;" alt="JCertif Logo" src="cid:image"><br>
</div>

<div class="container2">
<div class="pagetitlesuccess">Votre nouveau mot de passe !</div>
<p>
   Bonjour $participant.salutation$ $participant.prenom$ $participant.nom$,<br/><br/>
   
   Voici votre nouveau mot de passe : $password$
   
<br/>
<br/>
   Vous pouvez vous connecter et r&eacute;aliser votre agenda personnalis&eacute; sur <a href="http://www.jcertif.com/" target="_blank">http://www.jcertif.com</a>
   
<br/>
<br/>

   ================================================<br />
   &Eacute;quipe JCertif 2011 - <a href="http://www.jcertif.com/" target="_blank" style="color: rgb(0, 0, 204);">http://www.jcertif.com</a><br />
   info@jcertif.com
</p>
</div>
<hr />

<div align="center">
<b>Sponsors</b>
<table>
	<tr>
		$partenaires$
	</tr>
</table>	
</div>



</div>

</body>
</html>